### ISSUE TITLE
how do you install this since a dependency, sharp, has an install script, but I have ignore-scripts as a default for safety reasons

### ISSUE THREAD

**Issue by NullVoxPopuli** [simonihmig/responsive-image#333]
There must be a way to manually run sharp's install hook :thinking:

**Comment by NullVoxPopuli** [comment]
found this -- https://github.com/lovell/sharp/issues/2462 no solution yet tho

**Comment by NullVoxPopuli** [comment]
I came up with a hack / workaround here: https://github.com/lovell/sharp/issues/3351

**Comment by simonihmig** [comment]
Closing this as https://github.com/lovell/sharp/issues/3750 seems to have fixed that
