### ISSUE TITLE
Images with similar filenames aren't getting picked up.

### ISSUE THREAD

**Issue by nova-alex** [simonihmig/responsive-image#450]
I've inherited a lot of images from a previous iteration of our product and some of them are numbered sequentially for example 

 - animals-bear.jpg
 - animals-bear-2.jpg

For some reason, in certain cases, filenames sharing the same initial character sequence as another file, such as `animals-bear-copy.jpg` which shares the same initial sequence with `animals-bear.jpg` are not copied into `/dist` or present when running `ember s`

Whereas `animals-cat.jpg`, `animals-dog.jpg` and `animals-bear.jpg` will all get processed, `animals-bear-*.jpg`, `animals-cat-*.jpg` and `animals-dog-*.jpg` will largely be omitted.

Here is a sample list which I tested:

| (original) Filename  | (expected) Responsive Filename           | in `/dist`?  |
| ------------- |:-------------|:-----:|
| animals-bear.jpg               | animals-bear1024w.jpg          |✔️|
| animals-bear - Copy.jpg        | animals-bear - Copy1024w.jpg        |✔️|
| animals-bear-copy - Copy.jpg   | animals-bear-copy - Copy1024w.jpg   |❌ |
| animals-bear-copy.jpg          | animals-bear-copy1024w.jpg          |❌ |
| animals-cat.jpg                | animals-cat1024w.jpg                |✔️|
| animals-cat-2.jpg              | animals-cat-21024w.jpg              |❌ |
| animals-dog.jpg                | animals-dog1024w.jpg                |✔️|
| animals-dog-v2.jpg             | animals-dog-v21024w.jpg             |❌ |
| animals-dog-version2.jpg       | animals-dog-version21024w.jpg       |❌ |
| animals-dog-version-b.jpg      | animals-dog-version-b1024w.jpg      |❌ |
| numbers-digital-1.jpg        | numbers-digital-11024w.jpg        |✔️|
| numbers-digital-10.jpg        | numbers-digital-101024w.jpg        |✔️|
| numbers-digital-one.jpg        | numbers-digital-one1024w.jpg        |✔️|
| numbers-digital-one-hundred.jpg        | numbers-digital-one-hundred1024w.jpg        |❌|

View of /public/assets/images
![image](https://user-images.githubusercontent.com/116140250/212459095-22b29eaa-154b-4a92-bfa3-eae0fb39ecbe.png)

Output of /dist/assets/images
![image](https://user-images.githubusercontent.com/116140250/212459102-0ce4107e-3268-4eac-a012-ed8c04ba2f42.png)

I'm kind of stumped as to why this would happen, I'm guessing perhaps a regex of some sort. Any advice is appreciated!

**Comment by simonihmig** [comment]
Closing this, as the new upcoming release is a complete rewrite of this library will most likely not suffer from this.
