### ISSUE TITLE
Vite loader support

### ISSUE THREAD

**Issue by lifeart** [simonihmig/responsive-image#552]
It will be great to have `vite` support for responsive image (future embroider).

In addition, I checking possibilities to add `ember-responsive-image` to https://github.com/lifeart/glimmer-next demo website.

Side notes:

1. Seems we could simplify addon a bit (replace service with pojo) 
2. We could replace `dependencySatisfies` with bundler-related loader logic, not using `embroider` specific functions. (sounds less embroider native, but not require runtime transpilation/transformation and could be combined with `define` plugins)
```js
import vitePlugin from "ember-responsive-image/vite";

export default viteConfig = {
  plugins: [plugin({ blurhash: true })],
};

// implementation
function vitePlugin(config) {
  return {
    enforce: "pre",
    name: "ember-responsive-image",
    config(original) {
        return {
            define: {
                HAS_BLURHASH: config.blurhash === true
            }
        }
    }
  };
}

```

**Comment by simonihmig** [comment]
> It will be great to have vite support

Yeah, that's definitely something we need, at least when Vite support in Embroider becomes more or less stable

> We could replace dependencySatisfies with bundler-related loader logic, not using embroider specific functions.

What's the benefit? It wouldn't strip unused code (I admit it's not a lot), would it?

**Comment by lifeart** [comment]
> What's the benefit? It wouldn't strip unused code (I admit it's not a lot), would it?

Yep, code splitting should work. What's the benefit? - less 3rd party dependencies, clear logic, ability to use in non-embroider environments.

**Comment by HriBB** [comment]
Is it possible to use this package with React instead of ember? I am using Remix with Vite, so i should be able to use the vite plugin and build my own React component, right?

**Comment by simonihmig** [comment]
Available as of https://github.com/simonihmig/responsive-image/releases/tag/%40responsive-image%2Fvite-plugin%401.0.0-beta.1

**Comment by HriBB** [comment]
So I was able to use the vite plugin in a React project 🎉 Unfortunately, the `lqip` config does not work. Will open a new issue for that.

Still work in progress, but I can make a PR for a ResponsiveImage React component, if you are interested.
