### ISSUE TITLE
published @responsive-image/webpack package is empty 

### ISSUE THREAD

**Issue by poulet42** [simonihmig/responsive-image#603]
👋 @simonihmig 

After following the readme instructions and installing @responsive-image/webpack with `pnpm add @responsive-image/webpack`. I hit an error `Cannot find module [...]/node_modules/@responsive-image/webpack/dist/index.cjs`. Looking at the content of the package. it seems there is no `dist` in there. (this is not an issue with the `@responsive-image/ember` package.

**Comment by simonihmig** [comment]
Thanks for reporting! There was indeed a misconfiguration. 🤦‍♂️ 

Should get fixed by #604, will cut a new release for `@responsive-image/webpack`!
